spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: http://library-service:8081
          predicates:
            - Path=/library/**
        - id: book-service
          uri: http://book-service:8082
          predicates:
            - Path=/books/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true